# Generated by Django 5.0.7 on 2024-07-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('modelo_contratacao', models.CharField(max_length=15)),
                ('senioridade', models.CharField(max_length=20)),
                ('site_busca', models.CharField(max_length=15)),
            ],
        ),
    ]
